### ISSUE TITLE
Photo in Student Info

### ISSUE THREAD

**Issue by devbizzy** [StudentVue-Community/StudentVue.js#3]
When I use `getStudentInfo` function, it has the photo key & its value is just a huge letters & numbers. Why is this & how am I supposed to use it to get the photo url?

![image](https://user-images.githubusercontent.com/57771087/115745060-16867d80-a361-11eb-88d4-748c056216af.png)
This is just a small image, its way longer.

**Comment by LoganMD** [comment]
That's the raw image, you should be able to turn that into a png file and get a working photo. Do keep in mind that StudentVUE stores the photos at very low res

**Comment by devbizzy** [comment]
> That's the raw image, you should be able to turn that into a png file and get a working photo. Do keep in mind that StudentVUE stores the photos at very low res

alright thanks for the tip.

**Comment by devbizzy** [comment]
> That's the raw image, you should be able to turn that into a png file and get a working photo. Do keep in mind that StudentVUE stores the photos at very low res

How would I do that? I've looked online but I can't find a converter or an API that does the conversion.

**Comment by LoganMD** [comment]
If you wanna make it into a png file just make a .png file and put that string into it

**Comment by devbizzy** [comment]
I'm guessing you mean this..this is what happens when I do it though.
![image](https://user-images.githubusercontent.com/57771087/115868206-155d5b00-a40a-11eb-964d-a684db26bae7.png)
![image](https://user-images.githubusercontent.com/57771087/115868286-39b93780-a40a-11eb-956f-01f324686ab8.png)
![image](https://user-images.githubusercontent.com/57771087/115868313-463d9000-a40a-11eb-8c98-661f7508ce7c.png)
![image](https://user-images.githubusercontent.com/57771087/115868330-4ccc0780-a40a-11eb-8388-da091885b5b0.png)
![image](https://user-images.githubusercontent.com/57771087/115868347-535a7f00-a40a-11eb-9a3d-dab43692d1a3.png)

**Comment by devbizzy** [comment]
![image](https://user-images.githubusercontent.com/57771087/115868550-a03e5580-a40a-11eb-99ae-91eddb53a248.png)
This is also whats rendered when I open the file in a browser

**Comment by LoganMD** [comment]
Might be jpg then, I haven't messed with StudentVUE in a while so I'm not certain

**Comment by devbizzy** [comment]
> Might be jpg then, I haven't messed with StudentVUE in a while so I'm not certain

That also shows the same result unfortunately.

**Comment by kaijchang** [comment]
@Bxzzy didn't see this until now, try https://codebeautify.org/base64-to-image-converter if you're still interested.

**Comment by devbizzy** [comment]
> @Bxzzy didn't see this until now, try https://codebeautify.org/base64-to-image-converter if you're still interested.

thanks man, will use this sooner or later!
