### ISSUE TITLE
client.getSchedule(termIndex) not working

### ISSUE THREAD

**Issue by themirrazz** [StudentVue-Community/StudentVue.js#6]
I try to input the term index and even `SchoolYearTrmCodeGU`, but it always returns the schedule for the current term. I know my school supports selecting the term because it works perfectly fine on the mobile app.

You can reproduce by running:

```js
const StudentVue=require("studentvue.js")
StudentVue.login("https://student-vue.my-school.edu/", "your-username", "yourPassword12345").then(client => {
    client.getSchedule(1).then(schedule => console.log(schedule))
})
```

**Comment by kaijchang** [comment]
@themirrazz Unfortunately this library is no longer maintained. However, if you find a fix feel free to submit a pull request. Thanks!

**Comment by themirrazz** [comment]
OK
